# Generated by Django 4.1.2 on 2022-10-06 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='age',
        ),
        migrations.RemoveField(
            model_name='members',
            name='city',
        ),
    ]
